# Generated by Django 4.1.5 on 2023-01-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_skills', models.TextField()),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('salary_currency', models.FloatField()),
                ('area_name', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
