# Generated by Django 4.1.5 on 2023-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java_vacancies', '0003_top_vacancies_skillls_delete_top_skillls'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_vacancies_skillls',
            name='year',
            field=models.IntegerField(default='0'),
        ),
    ]
